### ISSUE TITLE
Read the barcode (not QRCode) in landscape mode

### ISSUE THREAD

**Issue by tattivitorino** [flutter-package/flutter_scan#26]
## Environment

**Flutter version:** (flutter doctor -v output)
```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-BR)
    • Flutter version 2.0.3 at /Users/tattivitorino/Tools/flutter
    • Framework revision 4d7946a68d (8 months ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tattivitorino/Library/Android/sdk
    • Platform android-31, build-tools 29.0.2
    • ANDROID_HOME = /Users/tattivitorino/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/tattivitorino/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0
```
**Plugin version:**  scan: ^1.5.0 
 
**Device information:**  Samsung A10 - Android 10

## Description

**What you'd like to happen:**
I'd like to be able to force the barcode reading to landscape mode because barcodes are bigger than qrcodes

**Alternatives you've considered:** I've tried ``` SystemChrome.setPreferredOrientations ``` to landscape but as soon as the camera starts it puts back to portrait.

**Images:** this is what i would like to achieve:

![image](https://user-images.githubusercontent.com/5480296/142205226-d7cd0915-775c-45ea-a5bc-10bd863cb83d.png)

any help will be very much appreciated!

**Comment by chavesgu** [comment]
you should set scale to 1.0，scan area will be the bigest

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tattivitorino ***@***.***&gt;;
发送时间：2021年11月17日(星期三) 晚上9:00
收件人："flutter-package/flutter_scan" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[flutter-package/flutter_scan] Read the barcode (not QRCode) in landscape mode (Issue #26)
-----------------------------------

 

 
Environment
 
Flutter version: (flutter doctor -v output)
 [✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-BR)     • Flutter version 2.0.3 at /Users/tattivitorino/Tools/flutter     • Framework revision 4d7946a68d (8 months ago), 2021-03-18 17:24:33 -0700     • Engine revision 3459eb2436     • Dart version 2.12.2 [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)     • Android SDK at /Users/tattivitorino/Library/Android/sdk     • Platform android-31, build-tools 29.0.2     • ANDROID_HOME = /Users/tattivitorino/Library/Android/sdk     • ANDROID_SDK_ROOT = /Users/tattivitorino/Library/Android/sdk     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)     • All Android licenses accepted. [✓] Xcode - develop for iOS and macOS     • Xcode at /Applications/Xcode.app/Contents/Developer     • Xcode 12.1, Build version 12A7403     • CocoaPods version 1.10.1 [✓] Chrome - develop for the web     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome [✓] Android Studio (version 4.0)     • Android Studio at /Applications/Android Studio.app/Contents     • Flutter plugin version 51.0.1     • Dart plugin version 193.7547     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593) [✓] VS Code (version 1.62.2)     • VS Code at /Applications/Visual Studio Code.app/Contents     • Flutter extension version 3.28.0  
Plugin version:  scan: ^1.5.0
 
Device information:  Samsung A10 - Android 10
 
Description
 
What you'd like to happen:
 I'd like to be able to force the barcode reading to landscape mode because barcodes are bigger than qrcodes
 
Alternatives you've considered: I've tried SystemChrome.setPreferredOrientations to landscape but as soon as the camera starts it puts back to portrait.
 
Images: this is what i would like to achieve:
 

 
any help will be very much appreciated!
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tattivitorino** [comment]
@chavesgu thx for your reply! 
I tried the scale to 1 and yet it doesnt meet the requirements I have! I need it to be in landscape mode.

**Comment by chavesgu** [comment]
not support

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tattivitorino ***@***.***&gt;;
发送时间：2021年11月17日(星期三) 晚上11:08
收件人："flutter-package/flutter_scan" ***@***.***&gt;;
抄送："Chaves Gu ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [flutter-package/flutter_scan] Read the barcode (not QRCode) in landscape mode (Issue #26)
-----------------------------------

 

 
@chavesgu thx for your reply!
 I tried the scale to 1 and yet it doesnt meet the requirements I have! I need it to be in landscape mode.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
